-- Migration: create_fdw_dim_team_opponent_stats
-- Creates foreign table for BigQuery dim_team_opponent_stats (67 defensive stat columns + ranks)
-- Source: Mateus created this mart with per-category defensive rankings (pts/reb/ast/3pt% cedidos, paint, rim protection, etc.)
-- 30 rows (one per team), season 2025.

DROP FOREIGN TABLE IF EXISTS bigquery.dim_team_opponent_stats;

CREATE FOREIGN TABLE bigquery.dim_team_opponent_stats (
  team_id                bigint,
  team_name              text,
  team_abbreviation      text,
  season                 bigint,
  opp_pts                double precision,
  opp_pts_rank           bigint,
  opp_reb                double precision,
  opp_reb_rank           bigint,
  opp_oreb               double precision,
  opp_oreb_rank          bigint,
  opp_dreb               double precision,
  opp_dreb_rank          bigint,
  opp_ast                double precision,
  opp_ast_rank           bigint,
  opp_fg_pct             double precision,
  opp_fg_pct_rank        bigint,
  opp_fg3_pct            double precision,
  opp_fg3_pct_rank       bigint,
  opp_stl                double precision,
  opp_stl_rank           bigint,
  opp_blk                double precision,
  opp_blk_rank           bigint,
  opp_tov                double precision,
  opp_tov_rank           bigint,
  opp_fta                double precision,
  opp_fta_rank           bigint,
  opp_ft_pct             double precision,
  opp_ft_pct_rank        bigint,
  def_rating             double precision,
  def_rating_rank        bigint,
  opp_pts_paint          double precision,
  opp_pts_paint_rank     bigint,
  opp_pts_2nd_chance     double precision,
  opp_pts_2nd_chance_rank bigint,
  opp_pts_off_tov        double precision,
  opp_pts_off_tov_rank   bigint,
  opp_pts_fb             double precision,
  opp_pts_fb_rank        bigint,
  dreb_pct               double precision,
  dreb_pct_rank          bigint,
  oreb_chance_pct        double precision,
  dreb_chance_pct        double precision,
  reb_chance_pct         double precision,
  oreb_chances           double precision,
  dreb_chances           double precision,
  oreb_contest_pct       double precision,
  dreb_contest_pct       double precision,
  avg_reb_dist           double precision,
  cs_fga                 double precision,
  cs_fga_frequency       double precision,
  cs_fg3a                double precision,
  cs_fg3a_frequency      double precision,
  cs_fg_pct              double precision,
  cs_fg3_pct             double precision,
  cs_efg_pct             double precision,
  pullup_fga             double precision,
  pullup_fga_frequency   double precision,
  pullup_fg3a            double precision,
  pullup_fg3a_frequency  double precision,
  pullup_fg_pct          double precision,
  pullup_fg3_pct         double precision,
  pullup_efg_pct         double precision,
  def_rim_fga            double precision,
  def_rim_fgm            double precision,
  def_rim_fg_pct         double precision,
  def_rim_fg_pct_rank    bigint,
  loaded_at              timestamp
)
SERVER bigquery_wrapper_server
OPTIONS (
  table 'dim_team_opponent_stats',
  location 'us-east1'
);
