// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lavclmlvvfzkblrstojd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdmNsbWx2dmZ6a2JscnN0b2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTUxMDMsImV4cCI6MjA2ODM3MTEwM30.LxgXqtBaggvnbnlfTawqroqj4rG2eIVmbJSWP55Ee1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});